brew "asdf"
brew "autojump"
brew "bat"
brew "chruby"
brew "chruby-fish"
brew "coreutils"
brew "cowsay"
brew "ctags"
brew "datamash"
brew "direnv"
brew "erlang"
brew "fd"
brew "fish"
brew "fpp"
brew "fzy"
brew "git"
brew "gnu-typist"
brew "go"
brew "httpie"
brew "hub"
brew "ipfs"
brew "jq"
brew "leiningen"
brew "neovim"
brew "node"
brew "npm"
brew "opam"
brew "pup"
brew "python"
brew "python3"
brew "reattach-to-user-namespace"
brew "ripgrep"
brew "rlwrap"
brew "ruby-install"
brew "saulpw/vd/visidata"
brew "selecta"
brew "stow"
brew "tmux"
brew "trash"
brew "tree"
brew "vcprompt"
brew "vim"
brew "watchman"
brew "webkit2png"
brew "wget"
brew "xsv"
brew "yarn"
brew "youtube-dl"

cask "blender"
cask "calibre"
cask "charles"
cask "choosy"
cask "colorpicker-skalacolor"
cask "docker"
cask "firefox"
cask "font-camingocode"
cask "font-hasklig"
cask "font-inconsolata-lgc"
cask "font-office-code-pro"
cask "font-open-sans"
cask "fontforge"
cask "google-chrome"
cask "intellij-idea-ce"
cask "kaleidoscope"
cask "karabiner-elements"
cask "openemu"
cask "paparazzi"
cask "paw"
cask "postgres-unofficial"
cask "postico"
cask "qlstephen"
cask "quicknfo"
cask "racket"
cask "satellite-eyes"
cask "slack"
cask "spotify"
cask "switchresx"
cask "the-unarchiver"
cask "vlc"
cask "xquartz"
cask "xscreensaver"

mas "1Blocker", id: 1365531024
mas "Boop", id: 1518425043
mas "Mela", id: 1568924476
mas "MetaDoctor", id: 988250390
mas "Moom", id: 419330170
mas "Pixelmator Pro", id: 1289583905
mas "Tot", id: 1491071483
mas "iA Writer", id: 775737590
