" gvim config
" Copy to ~/.gvimrc or ~/_gvimrc.

set guifont=Inconsolata-dz:h14    " Font family and font size.
set antialias                     " MacVim: smooth fonts.
set encoding=utf-8                " Use UTF-8 everywhere.
set guioptions-=T                 " Hide toolbar.
set background=light              " Background.
set lines=55 columns=100          " Window dimensions.

colorscheme solarized

set guioptions-=r                 " Don't show right scrollbar
set guioptions-=R
set guioptions-=l                 " ...or the left one
set guioptions-=L

" expand window in fullscreen 
set fuoptions=maxvert,maxhorz

map <D-1> :CommandT<CR>

" command-t file browser
if has("gui_macvim")
  macmenu &File.New\ Tab key=<nop>
  map <D-t> :CommandT<CR>
endif

" command-; for : 
"if has("gui_macvim")
"    macmenu &File.New\ Tab key=<nop>
"    map <D-o>l<CR>
"endif

" command-1 for bufferexplorer: 
"if has("gui_macvim")
"    map <D-1>:NERDTree<CR>
"endif

