# diameter_compile: Deroffing man parser
# Autogenerated from man pages
complete -c diameter_compile -s o --description 'Specifies the directory into which the genera... [See Man Page]'
complete -c diameter_compile -s i --description 'Specifies a directory to add to the code path... [See Man Page]'
complete -c diameter_compile -o E:
complete -c diameter_compile -o H: --description 'Supresses erl and hrl generation, respectivel... [See Man Page]'
complete -c diameter_compile -l name
complete -c diameter_compile -l prefix --description 'Set @name and @prefix in the dictionary, resp... [See Man Page]'
complete -c diameter_compile -l inherits --description 'Append an @inherits to the dictionary before ... [See Man Page]'

