# dirmngr-client: Deroffing man parser
# Autogenerated from man pages
complete -c dirmngr-client -l version --description 'Print the program version and licensing infor... [See Man Page]'
complete -c dirmngr-client -l help -s h --description 'Print a usage message summarizing the most us... [See Man Page]'
complete -c dirmngr-client -l quiet -s q --description 'Make the output extra brief by suppressing an... [See Man Page]'
complete -c dirmngr-client -l verbose --description 'Outputs additional information while running'
complete -c dirmngr-client -l pem --description 'Assume that the given certificate is in PEM (... [See Man Page]'
complete -c dirmngr-client -l ocsp --description 'Do the check using the OCSP protocol and igno... [See Man Page]'
complete -c dirmngr-client -l force-default-responder --description 'When checking using the OCSP protocl, force t... [See Man Page]'
complete -c dirmngr-client -l ping --description 'Check whether the dirmngr daemon is up and ru... [See Man Page]'
complete -c dirmngr-client -l cache-cert --description 'Put the given certificate into the cache of a... [See Man Page]'
complete -c dirmngr-client -l validate --description 'Validate the given certificate using dirmngr\'... [See Man Page]'
complete -c dirmngr-client -l load-crl --description 'This command expects a list of filenames with... [See Man Page]'
complete -c dirmngr-client -l lookup --description 'Take the remaining arguments and run a lookup... [See Man Page]'
complete -c dirmngr-client -s u --description 'Modify the lookup and load-crl commands to ta... [See Man Page]'
complete -c dirmngr-client -s l --description 'Let the lookup command only search the local ... [See Man Page]'
complete -c dirmngr-client -s v
complete -c dirmngr-client -l url
complete -c dirmngr-client -l local
complete -c dirmngr-client -l squid-mode --description 'Run dirmngr-client in a mode suitable as a he... [See Man Page]'

