# fsc: Deroffing man parser
# Autogenerated from man pages
complete -c fsc -o reset --description 'Reset compile server caches'
complete -c fsc -o shutdown --description 'Shut down the compilation daemon'
complete -c fsc -o server --description 'Specify compile server host at port number'
complete -c fsc -s J --description 'Pass <flag> directly to the Java VM for the c... [See Man Page]'

