# marked: Deroffing man parser
# Autogenerated from man pages
complete -c marked -s o -l 'output[output]' --description 'Specify file output'
complete -c marked -s i -l 'input[input]' --description 'Specify file input, otherwise use last argume... [See Man Page]'
complete -c marked -s t -l tokens --description 'Output a token stream instead of html'
complete -c marked -l pedantic --description 'Conform to obscure parts of markdown'
complete -c marked -l gfm --description 'Enable github flavored markdown'
complete -c marked -l sanitize --description 'Sanitize output'
complete -c marked -l output --description 'Specify file output'
complete -c marked -l input --description 'Specify file input, otherwise use last argume... [See Man Page]'
complete -c marked -s h -l help --description 'Display help information'

