# optipng: Deroffing man parser
# Autogenerated from man pages
complete -c optipng -s '?' -s h -o help --description 'Show a complete summary of options'
complete -c optipng -o backup -o keep --description 'Keep a backup of the modified files'
complete -c optipng -o clobber --description 'Overwrite the existing output and backup file... [See Man Page]'
complete -c optipng -o dir --description 'Write the output files to directory'
complete -c optipng -o fix --description 'Enable error recovery'
complete -c optipng -o force --description 'Enforce writing of a new output file'
complete -c optipng -o log --description 'Log messages to file'
complete -c optipng -o out --description 'Write output file to file'
complete -c optipng -o preserve --description 'Preserve file attributes (time stamps, file a... [See Man Page]'
complete -c optipng -o quiet -o silent --description 'Run in quiet mode'
complete -c optipng -o simulate --description 'Run in simulation mode: perform the trials, b... [See Man Page]'
complete -c optipng -s v --description 'Enable the options -verbose and -version'
complete -c optipng -o verbose --description 'Run in verbose mode'
complete -c optipng -o version --description 'Show copyright, version and build info'
complete -c optipng -s o --description 'Select the optimization level'
complete -c optipng -s f --description 'Select the PNG delta filters'
complete -c optipng -o full --description 'Produce a full report on IDAT'
complete -c optipng -s i --description 'Select the interlace type (0-1)'
complete -c optipng -o nb --description 'Do not apply bit depth reduction'
complete -c optipng -o nc --description 'Do not apply color type reduction'
complete -c optipng -o np --description 'Do not apply palette reduction'
complete -c optipng -o nx --description 'Do not apply any lossless image reduction: en... [See Man Page]'
complete -c optipng -o nz --description 'Do not recode IDAT datastreams'
complete -c optipng -o zc --description 'Select the zlib compression levels used in ID... [See Man Page]'
complete -c optipng -o zm --description 'Select the zlib memory levels used in IDAT co... [See Man Page]'
complete -c optipng -o zs --description 'Select the zlib compression strategies used i... [See Man Page]'
complete -c optipng -o zw --description 'Select the zlib window size (32k,16k,8k,4k,2k... [See Man Page]'
complete -c optipng -o snip --description 'Cut one image out of multi-image, animation o... [See Man Page]'
complete -c optipng -o strip --description 'Strip metadata objects from a PNG file'
complete -c optipng -o o3
complete -c optipng -o f0
complete -c optipng -o f3-5
complete -c optipng -o zs0 -o zs1 -o zs2-3 -o zs0 -o zs0-3
complete -c optipng -o 'nx.' --description 'and may be fine-tuned via the options -zc, -z... [See Man Page]'
complete -c optipng -o 'zw.' --description 'being created, and may be fine-tuned via the ... [See Man Page]'

