# phpsh: Type1
# Autogenerated from man pages
complete -c phpsh -s c -l codebase-mode --description 'Use "-c none" to load no codebase'
complete -c phpsh -s t -l test-file --description 'Run a saved-phpsh-session unit test file'
complete -c phpsh -s v -l verbose --description 'Be more verbose, do not defer warnings about ... [See Man Page]'
complete -c phpsh -s A -l no-autocomplete --description 'Disable identifier autocomplete'
complete -c phpsh -s C -l no-color --description 'Do not try to change color for different type... [See Man Page]'
complete -c phpsh -s M -l no-multiline --description 'Disable support for multiline input'
complete -c phpsh -s T -l no-ctags --description 'Do not run ctags to index the code base'

