# pth-config: Type1
# Autogenerated from man pages
complete -c pth-config -l help --description 'Prints the short usage information'
complete -c pth-config -l version --description 'Prints the version number and date of the ins... [See Man Page]'
complete -c pth-config -l all --description 'Forces the output of all flags, that is, incl... [See Man Page]'
complete -c pth-config -l prefix --description 'Prints the installation prefix of architectur... [See Man Page]'
complete -c pth-config -l exec-prefix --description 'Prints the installation prefix of architectur... [See Man Page]'
complete -c pth-config -l bindir --description 'Prints the installation directory of binaries... [See Man Page]'
complete -c pth-config -l libdir --description 'Prints the installation directory of librarie... [See Man Page]'
complete -c pth-config -l includedir --description 'Prints the installation directory of include ... [See Man Page]'
complete -c pth-config -l mandir --description 'Prints the installation directory of manual p... [See Man Page]'
complete -c pth-config -l datadir --description 'Prints the installation directory of shared d... [See Man Page]'
complete -c pth-config -l acdir --description 'Prints the installation directory of autoconf... [See Man Page]'
complete -c pth-config -l cflags --description 'Prints the C compiler flags which are needed ... [See Man Page]'
complete -c pth-config -l ldflags --description 'Prints the linker flags (\\f(CW\\*(C`-L\\*(C\') w... [See Man Page]'

