# rubber-info: Deroffing man parser
# Autogenerated from man pages
complete -c rubber-info -l check --description 'is assumed'
complete -c rubber-info -l boxes --description 'Extracts from the log file the places in the ... [See Man Page]'
complete -c rubber-info -l deps --description 'Analyse the source files and produce a space-... [See Man Page]'
complete -c rubber-info -l errors --description 'Extract from the log file the list of errors ... [See Man Page]'
complete -c rubber-info -s h -l help --description 'Display the list of all available options and... [See Man Page]'
complete -c rubber-info -l refs --description 'Report the list of undefined or multiply defi... [See Man Page]'
complete -c rubber-info -l rules --description 'Analyse the source files and produce a list o... [See Man Page]'
complete -c rubber-info -l version --description 'Print the version number and exit nicely'
complete -c rubber-info -l warnings --description 'Stupidly enumerate all LaTeX warnings, i'

