# strfile: Deroffing man parser
# Autogenerated from man pages
complete -c strfile -s c --description 'Change the delimiting character from the perc... [See Man Page]'
complete -c strfile -s i --description 'Ignore case when ordering the strings'
complete -c strfile -s o --description 'Order the strings in alphabetical order'
complete -c strfile -s r --description 'Randomize access to the strings'
complete -c strfile -s s --description 'Run silently; don\'t give a summary message wh... [See Man Page]'
complete -c strfile -s x --description 'Note that each alphabetic character in the gr... [See Man Page]'

