# unstr: Deroffing man parser
# Autogenerated from man pages
complete -c unstr -s c --description 'Change the delimiting character from the perc... [See Man Page]'
complete -c unstr -s i --description 'Ignore case when ordering the strings'
complete -c unstr -s o --description 'Order the strings in alphabetical order'
complete -c unstr -s r --description 'Randomize access to the strings'
complete -c unstr -s s --description 'Run silently; don\'t give a summary message wh... [See Man Page]'
complete -c unstr -s x --description 'Note that each alphabetic character in the gr... [See Man Page]'

