# autojump: Deroffing man parser
# Autogenerated from man pages
complete -c autojump -s a -l add
complete -c autojump -l purge
complete -c autojump -s s -l stat
complete -c autojump -l version --description 'INTERNAL OPTIONS'
complete -c autojump -s b -l bash
complete -c autojump -l complete --description 'ADDITIONAL CONFIGURATION [bu] 2 Enable ZSH Ta... [See Man Page]'

