# cowthink: Deroffing man parser
# Autogenerated from man pages
complete -c cowthink -s n --description option
complete -c cowthink -s W --description 'specifies roughly (where the message should b... [See Man Page]'
complete -c cowthink -s b --description 'option initiates Borg mode; '
complete -c cowthink -s d --description 'causes the cow to appear dead; '
complete -c cowthink -s g --description 'invokes greedy mode;'
complete -c cowthink -s p --description 'causes a state of paranoia to come over the c... [See Man Page]'
complete -c cowthink -s s --description 'makes the cow appear thoroughly stoned;'
complete -c cowthink -s t --description 'yields a tired cow;'
complete -c cowthink -s w --description 'is somewhat the opposite of '
complete -c cowthink -s y --description 'brings on the cow\'s youthful appearance'
complete -c cowthink -s e --description 'option to select the appearance of the cow\'s ... [See Man Page]'
complete -c cowthink -s T --description 'and tongue_string ; it must be two characters... [See Man Page]'
complete -c cowthink -s f --description 'option specifies a particular cow picture fil... [See Man Page]'
complete -c cowthink -s l --description switch

