# git-column: Deroffing man parser
# Autogenerated from man pages
complete -c git-column -l command --description 'Look up layout mode using configuration varia... [See Man Page]'
complete -c git-column -l mode --description 'Specify layout mode'
complete -c git-column -l raw-mode --description 'Same as --mode but take mode encoded as a num... [See Man Page]'
complete -c git-column -l width --description 'Specify the terminal width'
complete -c git-column -l indent --description 'String to be printed at the beginning of each... [See Man Page]'
complete -c git-column -l nl --description 'String to be printed at the end of each line,... [See Man Page]'
complete -c git-column -l padding --description 'The number of spaces between columns'

