# ne: Deroffing man parser
# Autogenerated from man pages
complete -c ne -l help --description 'Prints a help message'
complete -c ne -l binary --description 'Load the next named file in binary mode'
complete -c ne -l utf8 --description 'Use UTF-8 I/O'
complete -c ne -l no-utf8 --description 'Do not use UTF-8 I/O'
complete -c ne -l ansi --description 'Use the built-in ANSI sequences'
complete -c ne -l no-ansi --description 'Never use the built-in ANSI sequences'
complete -c ne -l no-config --description 'Skip reading the menu and keyboard configurat... [See Man Page]'
complete -c ne -l no-syntax --description 'Disable syntax-highlighting support'
complete -c ne -l keys --description 'Use the specified keyboard configuration file... [See Man Page]'
complete -c ne -l menus --description 'Use the specified menu configuration file'
complete -c ne -l macro --description 'Execute the given macro after startup'

