# scaladoc: Deroffing man parser
# Autogenerated from man pages
complete -c scaladoc -s d --description 'Specify where to generate documentation'
complete -c scaladoc -o version --description 'Print product version and exit'
complete -c scaladoc -o help --description 'Print a synopsis of available options'
complete -c scaladoc -o doc-title --description 'Define the overall title of the documentation... [See Man Page]'
complete -c scaladoc -o doc-version --description 'Define the overall version number of the docu... [See Man Page]'
complete -c scaladoc -o doc-source-url --description 'Define a URL to be concatenated with source l... [See Man Page]'
complete -c scaladoc -o verbose --description 'Output messages about what the compiler is do... [See Man Page]'
complete -c scaladoc -o deprecation --description 'Indicate whether source should be compiled wi... [See Man Page]'
complete -c scaladoc -o classpath --description 'Specify where to find user class files (on Un... [See Man Page]'
complete -c scaladoc -o sourcepath --description 'Specify where to find input source files'
complete -c scaladoc -o bootclasspath --description 'Override location of bootstrap class files (w... [See Man Page]'
complete -c scaladoc -o extdirs --description 'Override location of installed extensions'
complete -c scaladoc -o encoding --description 'Specify character encoding used by source fil... [See Man Page]'

