# scalap: Deroffing man parser
# Autogenerated from man pages
complete -c scalap -o help --description 'Display this usage message'
complete -c scalap -o private --description 'Print private definitions'
complete -c scalap -o verbose --description 'Print out additional information'
complete -c scalap -o version --description 'Print product version and exit'
complete -c scalap -o cp -o classpath --description 'Specify where to find user class files'

