" gvim config
" Copy to ~/.gvimrc or ~/_gvimrc.

set guifont=Monaco:h12    " Font family and font size.
" set guifont=Inconsolata-dz:h14    " Font family and font size.
set noantialias                     " MacVim: aliased fonts.
" set antialias                     " MacVim: smooth fonts.
set encoding=utf-8                " Use UTF-8 everywhere.
set guioptions-=T                 " Hide toolbar.
set background=dark               " Background.
set lines=55 columns=85           " Window dimensions.

" colorscheme codeschool
colorscheme Tomorrow-Night

set guioptions-=r                 " Don't show right scrollbar
set guioptions-=R
set guioptions-=l                 " ...or the left one
set guioptions-=L

" expand window in fullscreen
set fuoptions=maxvert,maxhorz

map <D-j> <C-f>
map <D-k> <C-b>

